//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantDesktopClient.PriceService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PriceService.IPriceService")]
    public interface IPriceService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPriceService/CreatePrice", ReplyAction="http://tempuri.org/IPriceService/CreatePriceResponse")]
        void CreatePrice(ModelLibrary.Price price, int itemId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPriceService/CreatePrice", ReplyAction="http://tempuri.org/IPriceService/CreatePriceResponse")]
        System.Threading.Tasks.Task CreatePriceAsync(ModelLibrary.Price price, int itemId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPriceService/DeletePrice", ReplyAction="http://tempuri.org/IPriceService/DeletePriceResponse")]
        void DeletePrice(ModelLibrary.Price price, int itemId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPriceService/DeletePrice", ReplyAction="http://tempuri.org/IPriceService/DeletePriceResponse")]
        System.Threading.Tasks.Task DeletePriceAsync(ModelLibrary.Price price, int itemId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPriceService/GetPrice", ReplyAction="http://tempuri.org/IPriceService/GetPriceResponse")]
        ModelLibrary.Price GetPrice(int itemId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPriceService/GetPrice", ReplyAction="http://tempuri.org/IPriceService/GetPriceResponse")]
        System.Threading.Tasks.Task<ModelLibrary.Price> GetPriceAsync(int itemId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPriceService/GetAllPricesByItem", ReplyAction="http://tempuri.org/IPriceService/GetAllPricesByItemResponse")]
        ModelLibrary.Price[] GetAllPricesByItem(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPriceService/GetAllPricesByItem", ReplyAction="http://tempuri.org/IPriceService/GetAllPricesByItemResponse")]
        System.Threading.Tasks.Task<ModelLibrary.Price[]> GetAllPricesByItemAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPriceService/UpdatePrice", ReplyAction="http://tempuri.org/IPriceService/UpdatePriceResponse")]
        void UpdatePrice(ModelLibrary.Price beforePrice, ModelLibrary.Price afterPrice);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPriceService/UpdatePrice", ReplyAction="http://tempuri.org/IPriceService/UpdatePriceResponse")]
        System.Threading.Tasks.Task UpdatePriceAsync(ModelLibrary.Price beforePrice, ModelLibrary.Price afterPrice);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPriceServiceChannel : RestaurantDesktopClient.PriceService.IPriceService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PriceServiceClient : System.ServiceModel.ClientBase<RestaurantDesktopClient.PriceService.IPriceService>, RestaurantDesktopClient.PriceService.IPriceService {
        
        public PriceServiceClient() {
        }
        
        public PriceServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PriceServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PriceServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PriceServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void CreatePrice(ModelLibrary.Price price, int itemId) {
            base.Channel.CreatePrice(price, itemId);
        }
        
        public System.Threading.Tasks.Task CreatePriceAsync(ModelLibrary.Price price, int itemId) {
            return base.Channel.CreatePriceAsync(price, itemId);
        }
        
        public void DeletePrice(ModelLibrary.Price price, int itemId) {
            base.Channel.DeletePrice(price, itemId);
        }
        
        public System.Threading.Tasks.Task DeletePriceAsync(ModelLibrary.Price price, int itemId) {
            return base.Channel.DeletePriceAsync(price, itemId);
        }
        
        public ModelLibrary.Price GetPrice(int itemId) {
            return base.Channel.GetPrice(itemId);
        }
        
        public System.Threading.Tasks.Task<ModelLibrary.Price> GetPriceAsync(int itemId) {
            return base.Channel.GetPriceAsync(itemId);
        }
        
        public ModelLibrary.Price[] GetAllPricesByItem(string id) {
            return base.Channel.GetAllPricesByItem(id);
        }
        
        public System.Threading.Tasks.Task<ModelLibrary.Price[]> GetAllPricesByItemAsync(string id) {
            return base.Channel.GetAllPricesByItemAsync(id);
        }
        
        public void UpdatePrice(ModelLibrary.Price beforePrice, ModelLibrary.Price afterPrice) {
            base.Channel.UpdatePrice(beforePrice, afterPrice);
        }
        
        public System.Threading.Tasks.Task UpdatePriceAsync(ModelLibrary.Price beforePrice, ModelLibrary.Price afterPrice) {
            return base.Channel.UpdatePriceAsync(beforePrice, afterPrice);
        }
    }
}
