//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserWebClient.RestaurantService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RestaurantService.IRestaurantService")]
    public interface IRestaurantService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRestaurantService/GetAllRestaurants", ReplyAction="http://tempuri.org/IRestaurantService/GetAllRestaurantsResponse")]
        ModelLibrary.Restaurant[] GetAllRestaurants();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRestaurantService/GetAllRestaurants", ReplyAction="http://tempuri.org/IRestaurantService/GetAllRestaurantsResponse")]
        System.Threading.Tasks.Task<ModelLibrary.Restaurant[]> GetAllRestaurantsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRestaurantService/GetAllRestaurantsByCategory", ReplyAction="http://tempuri.org/IRestaurantService/GetAllRestaurantsByCategoryResponse")]
        ModelLibrary.Restaurant[] GetAllRestaurantsByCategory(int categoryId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRestaurantService/GetAllRestaurantsByCategory", ReplyAction="http://tempuri.org/IRestaurantService/GetAllRestaurantsByCategoryResponse")]
        System.Threading.Tasks.Task<ModelLibrary.Restaurant[]> GetAllRestaurantsByCategoryAsync(int categoryId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRestaurantService/CreateRestaurant", ReplyAction="http://tempuri.org/IRestaurantService/CreateRestaurantResponse")]
        void CreateRestaurant(ModelLibrary.Restaurant restaurant);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRestaurantService/CreateRestaurant", ReplyAction="http://tempuri.org/IRestaurantService/CreateRestaurantResponse")]
        System.Threading.Tasks.Task CreateRestaurantAsync(ModelLibrary.Restaurant restaurant);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRestaurantService/UpdateRestaurant", ReplyAction="http://tempuri.org/IRestaurantService/UpdateRestaurantResponse")]
        void UpdateRestaurant(ModelLibrary.Restaurant restaurant);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRestaurantService/UpdateRestaurant", ReplyAction="http://tempuri.org/IRestaurantService/UpdateRestaurantResponse")]
        System.Threading.Tasks.Task UpdateRestaurantAsync(ModelLibrary.Restaurant restaurant);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRestaurantService/DeleteRestaurant", ReplyAction="http://tempuri.org/IRestaurantService/DeleteRestaurantResponse")]
        void DeleteRestaurant(ModelLibrary.Restaurant restaurant);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRestaurantService/DeleteRestaurant", ReplyAction="http://tempuri.org/IRestaurantService/DeleteRestaurantResponse")]
        System.Threading.Tasks.Task DeleteRestaurantAsync(ModelLibrary.Restaurant restaurant);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRestaurantService/GetAllRestaurantCategories", ReplyAction="http://tempuri.org/IRestaurantService/GetAllRestaurantCategoriesResponse")]
        ModelLibrary.RestaurantCategory[] GetAllRestaurantCategories();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRestaurantService/GetAllRestaurantCategories", ReplyAction="http://tempuri.org/IRestaurantService/GetAllRestaurantCategoriesResponse")]
        System.Threading.Tasks.Task<ModelLibrary.RestaurantCategory[]> GetAllRestaurantCategoriesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRestaurantService/CreateTable", ReplyAction="http://tempuri.org/IRestaurantService/CreateTableResponse")]
        void CreateTable(ModelLibrary.Table table);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRestaurantService/CreateTable", ReplyAction="http://tempuri.org/IRestaurantService/CreateTableResponse")]
        System.Threading.Tasks.Task CreateTableAsync(ModelLibrary.Table table);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRestaurantService/GetAllTables", ReplyAction="http://tempuri.org/IRestaurantService/GetAllTablesResponse")]
        ModelLibrary.Table[] GetAllTables(ModelLibrary.Restaurant restaurant);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRestaurantService/GetAllTables", ReplyAction="http://tempuri.org/IRestaurantService/GetAllTablesResponse")]
        System.Threading.Tasks.Task<ModelLibrary.Table[]> GetAllTablesAsync(ModelLibrary.Restaurant restaurant);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRestaurantService/GetTable", ReplyAction="http://tempuri.org/IRestaurantService/GetTableResponse")]
        ModelLibrary.Table[] GetTable(ModelLibrary.Table table);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRestaurantService/GetTable", ReplyAction="http://tempuri.org/IRestaurantService/GetTableResponse")]
        System.Threading.Tasks.Task<ModelLibrary.Table[]> GetTableAsync(ModelLibrary.Table table);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRestaurantService/UpdateTable", ReplyAction="http://tempuri.org/IRestaurantService/UpdateTableResponse")]
        void UpdateTable(ModelLibrary.Table table);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRestaurantService/UpdateTable", ReplyAction="http://tempuri.org/IRestaurantService/UpdateTableResponse")]
        System.Threading.Tasks.Task UpdateTableAsync(ModelLibrary.Table table);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRestaurantService/DeleteTable", ReplyAction="http://tempuri.org/IRestaurantService/DeleteTableResponse")]
        void DeleteTable(ModelLibrary.Table table);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRestaurantService/DeleteTable", ReplyAction="http://tempuri.org/IRestaurantService/DeleteTableResponse")]
        System.Threading.Tasks.Task DeleteTableAsync(ModelLibrary.Table table);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRestaurantServiceChannel : UserWebClient.RestaurantService.IRestaurantService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RestaurantServiceClient : System.ServiceModel.ClientBase<UserWebClient.RestaurantService.IRestaurantService>, UserWebClient.RestaurantService.IRestaurantService {
        
        public RestaurantServiceClient() {
        }
        
        public RestaurantServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RestaurantServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RestaurantServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RestaurantServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ModelLibrary.Restaurant[] GetAllRestaurants() {
            return base.Channel.GetAllRestaurants();
        }
        
        public System.Threading.Tasks.Task<ModelLibrary.Restaurant[]> GetAllRestaurantsAsync() {
            return base.Channel.GetAllRestaurantsAsync();
        }
        
        public ModelLibrary.Restaurant[] GetAllRestaurantsByCategory(int categoryId) {
            return base.Channel.GetAllRestaurantsByCategory(categoryId);
        }
        
        public System.Threading.Tasks.Task<ModelLibrary.Restaurant[]> GetAllRestaurantsByCategoryAsync(int categoryId) {
            return base.Channel.GetAllRestaurantsByCategoryAsync(categoryId);
        }
        
        public void CreateRestaurant(ModelLibrary.Restaurant restaurant) {
            base.Channel.CreateRestaurant(restaurant);
        }
        
        public System.Threading.Tasks.Task CreateRestaurantAsync(ModelLibrary.Restaurant restaurant) {
            return base.Channel.CreateRestaurantAsync(restaurant);
        }
        
        public void UpdateRestaurant(ModelLibrary.Restaurant restaurant) {
            base.Channel.UpdateRestaurant(restaurant);
        }
        
        public System.Threading.Tasks.Task UpdateRestaurantAsync(ModelLibrary.Restaurant restaurant) {
            return base.Channel.UpdateRestaurantAsync(restaurant);
        }
        
        public void DeleteRestaurant(ModelLibrary.Restaurant restaurant) {
            base.Channel.DeleteRestaurant(restaurant);
        }
        
        public System.Threading.Tasks.Task DeleteRestaurantAsync(ModelLibrary.Restaurant restaurant) {
            return base.Channel.DeleteRestaurantAsync(restaurant);
        }
        
        public ModelLibrary.RestaurantCategory[] GetAllRestaurantCategories() {
            return base.Channel.GetAllRestaurantCategories();
        }
        
        public System.Threading.Tasks.Task<ModelLibrary.RestaurantCategory[]> GetAllRestaurantCategoriesAsync() {
            return base.Channel.GetAllRestaurantCategoriesAsync();
        }
        
        public void CreateTable(ModelLibrary.Table table) {
            base.Channel.CreateTable(table);
        }
        
        public System.Threading.Tasks.Task CreateTableAsync(ModelLibrary.Table table) {
            return base.Channel.CreateTableAsync(table);
        }
        
        public ModelLibrary.Table[] GetAllTables(ModelLibrary.Restaurant restaurant) {
            return base.Channel.GetAllTables(restaurant);
        }
        
        public System.Threading.Tasks.Task<ModelLibrary.Table[]> GetAllTablesAsync(ModelLibrary.Restaurant restaurant) {
            return base.Channel.GetAllTablesAsync(restaurant);
        }
        
        public ModelLibrary.Table[] GetTable(ModelLibrary.Table table) {
            return base.Channel.GetTable(table);
        }
        
        public System.Threading.Tasks.Task<ModelLibrary.Table[]> GetTableAsync(ModelLibrary.Table table) {
            return base.Channel.GetTableAsync(table);
        }
        
        public void UpdateTable(ModelLibrary.Table table) {
            base.Channel.UpdateTable(table);
        }
        
        public System.Threading.Tasks.Task UpdateTableAsync(ModelLibrary.Table table) {
            return base.Channel.UpdateTableAsync(table);
        }
        
        public void DeleteTable(ModelLibrary.Table table) {
            base.Channel.DeleteTable(table);
        }
        
        public System.Threading.Tasks.Task DeleteTableAsync(ModelLibrary.Table table) {
            return base.Channel.DeleteTableAsync(table);
        }
    }
}
